---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  annotations:
    app.kubernetes.io/helm-template: {{ $.Template.Name }}
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ $.Values.namespace }}
  namespace: {{ $.Values.namespace }}
spec:
  eda:
    disabled: false
  route_tls_termination_mechanism: Edge
  no_log: true
  redis_mode: standalone
  image_pull_policy: IfNotPresent
  lightspeed:
    disabled: true
  hub:
    disabled: false
    pulp_settings:
    file_storage_size: 100Gi
    file_storage_storage_class: {{ $.Values.storageClassName }}
    storage_type: file
  controller:
    disabled: false
