{{ range $appProject := .Values.appProjects }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $appProject.name }}
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ squote $appProject.gitUrl }}
  project: {{ $appProject.name }}
{{ end }}
