{{ $Labels := include "labels" . }}
{{ range $appProject := .Values.appProjects }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $appProject.name }}
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: {{ $appProject.targetNamespace | default $appProject.name }}
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - {{ squote $appProject.gitUrl }}
  sourceNamespaces:
  - {{ $appProject.targetNamespace | default $appProject.name }}
{{ end }}
