{{ $Labels := include "labels" . }}
{{ range $appProject := .Values.appProjects }}
---
kind: Secret
apiVersion: v1
metadata:
  annotations:
    app.kubernetes.io/helm-template: {{ quote $.Template.Name }}
  labels:
    {{- $Labels | nindent 4 }}
    argocd.argoproj.io/secret-type: repository
  name: {{ $appProject.name }}
  namespace: openshift-gitops
stringData:
  project: {{ $appProject.name }}
  type: git
  url: {{ squote $appProject.gitUrl }}
type: Opaque
{{ end }}
