---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: {{ $.Values.name }}
  namespace: {{ $.Values.namespace }}
spec:
  {{- if ne false $.Values.singleNS }}
  targetNamespaces:
    - {{ $.Values.namespace }}
  {{- end }}
  upgradeStrategy: Default
