---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    app.kubernetes.io/helm-template: {{ quote $.Template.Name }}
  labels:
    {{- include "labels" . | nindent 4 }}
    operators.coreos.com/{{ $.Values.name }}.{{ $.Values.namespace }}: ""
  name: {{ $.Values.name }}
  namespace: {{ $.Values.namespace }}
spec:
  channel: {{ $.Values.channel | default "stable" }}
  name: {{ $.Values.name }}
  source: {{ $.Values.source | default "redhat-operators" }}
  sourceNamespace: openshift-marketplace
