---
#Refrences

#appProject.name := Name of Argo APP project, namespace
#appProject.description := Namespace description
#appProject.DisplayName := Namespace DisplayName
#appProject.gitUrl := Git URL for application helm charts (should end in ".git")
#appProject.gitBranch := Git Branch for respective application group (Defaults to "main")
#appProject.valuesFile := Values file for helm charts (Defaults to values.yaml)
#appProject.applications := List of applications to deploy into the project
#appProject.applications.name := UNIQUE Name for argo application
#appProject.applications.gitPath := Path inside the project gitUrl to the Helm chart


appProjects:
  - name: aap
    description: "Automation Automation Platform operator namespace"
    displayName: "Automation Automation Platform"
    gitUrl: 'https://github.com/jayissi/sample-gitops-aap.git'
    gitBranch: main
    valuesFile: values.yaml
    applications:
      - name: aap
        gitPath: operator
