---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  annotations:
    app.kubernetes.io/helm-template: {{ $.Template.Name }}
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ $.Values.namespace }}
  namespace: {{ $.Values.namespace }}
spec:
  eda:
    disabled: false
  route_tls_termination_mechanism: Edge
  no_log: true
  redis_mode: standalone
  image_pull_policy: IfNotPresent
  lightspeed:
    disabled: true
  hub:
    disabled: false
    pulp_settings:
      CONNECTED_ANSIBLE_CONTROLLERS: 
        - https://aap-controller-aap.{{ (lookup "config.openshift.io/v1" "Ingress" "" "cluster").spec.domain }}
    file_storage_size: 100Gi
    {{- $storageClasses := (lookup "storage.k8s.io/v1" "StorageClass" "" "").items -}}
    {{- $defaultStorageClass := "" }}
    {{- range $storageClasses }}
      {{- if and .metadata.annotations (eq (index .metadata.annotations "storageclass.kubernetes.io/is-default-class") "true") }}
        {{- $defaultStorageClass = .metadata.name }}
      {{- end }}
    {{- end }}
    {{- if or $.Values.storageClassName $defaultStorageClass }}
    file_storage_storage_class: {{ or $.Values.storageClassName $defaultStorageClass }}
    {{- end }}
    storage_type: file
  controller:
    disabled: false
  route_host: aap.{{ (lookup "config.openshift.io/v1" "Ingress" "" "cluster").spec.domain }}
