---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    app.kubernetes.io/helm-template: {{ $.Template.Name }}
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    {{- include "labels" . | nindent 4 }}
  name: argocd-aap
  namespace: {{ $.Values.namespace }}
rules:
- apiGroups:
  - aap.ansible.com
  resources:
  - ansibleautomationplatforms
  verbs:
  - create
  - get
  - list
  - update
  - patch
  - delete
