---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ $.Values.acm_policy_name }}-placement-binding
  namespace: aap
placementRef:
  name: {{ $.Values.acm_policy_name }}-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: {{ $.Values.acm_policy_name }}
    apiGroup: policy.open-cluster-management.io
    kind: Policy
