---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $.Values.acm_policy_name }}
  namespace: {{ $.Values.policy_namespace | default "default" }}
spec:
  disabled: false
  remediationAction: {{ $.Values.remediation_action | default "inform" }}
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-namespace
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  labels:
                    argocd.argoproj.io/managed-by: openshift-gitops
                  name: aap
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-operator-group
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: aap
                  namespace: aap
                spec: {}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-subscription
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: aap
                  namespace: aap
                spec:
                  name: ansible-automation-platform-operator
                  channel: {{ $.Values.channel }}
                  installPlanApproval: Automatic
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-operator-status
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: ClusterServiceVersion
                metadata:
                  namespace: aap
                spec:
                  displayName: Ansible Automation Platform
                status:
                  phase: Succeeded
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-controller
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: automationcontroller.ansible.com/v1beta1
                kind: AutomationController
                metadata:
                  name: {{ $.Values.name }}
                  namespace: aap
                spec:
                  hostname: {{ $.Values.name }}
                  create_preload_data: true
                  route_tls_termination_mechanism: Edge
                  garbage_collect_secrets: true
                  ingress_type: Route
                  loadbalancer_port: 80
                  no_log: true
                  image_pull_policy: IfNotPresent
                  projects_storage_size: 10Gi
                  auto_upgrade: true
                  task_privileged: false
                  projects_storage_access_mode: ReadWriteMany
                  set_self_labels: true
                  projects_persistence: true
                  replicas: 1
                  admin_user: admin
                  loadbalancer_protocol: http
                  nodeport_port: 30080
                  postgres_storage_class: ocs-storagecluster-ceph-rbd
                  projects_use_existing_claim: _No_
                  projects_storage_class: ocs-storagecluster-cephfs
                  admin_email: {{ $.Values.admin_email }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-hub
        spec:
          remediationAction: {{ $.Values.remediation_action | default "inform" }}
          severity: {{ $.Values.severity | default "low" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: automationhub.ansible.com/v1beta1
                kind: AutomationHub
                metadata:
                  name: example
                  namespace: aap
                spec:
                  nginx_proxy_send_timeout: 120s
                  gunicorn_content_workers: 2
                  gunicorn_api_workers: 2
                  route_tls_termination_mechanism: Edge
                  ingress_type: Route
                  loadbalancer_port: 80
                  no_log: true
                  file_storage_size: 100Gi
                  image_pull_policy: IfNotPresent
                  nginx_proxy_read_timeout: 120s
                  gunicorn_timeout: 90
                  nginx_client_max_body_size: 10m
                  web:
                    replicas: 1
                  nginx_proxy_connect_timeout: 120s
                  haproxy_timeout: 180s
                  file_storage_access_mode: ReadWriteMany
                  content:
                    log_level: INFO
                    replicas: 2
                  postgres_storage_requirements:
                    limits:
                      storage: 50Gi
                    requests:
                      storage: 8Gi
                  api:
                    log_level: INFO
                    replicas: 1
                  postgres_resource_requirements:
                    limits:
                      cpu: 1000m
                      memory: 8Gi
                    requests:
                      cpu: 500m
                      memory: 2Gi
                  redis:
                    log_level: INFO
                    replicas: 1
                  loadbalancer_protocol: http
                  resource_manager:
                    replicas: 1
                  worker:
                    replicas: 2
                  route_host: routedns
                  storage_type: File
                  file_storage_storage_class: ocs-storagecluster-cephfs
                  hostname: this is my hostname
                  postgres_storage_class: ocs-storagecluster-ceph-rbd
                  redis_storage_class: ocs-storagecluster-cephfs

